name: CD

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to target environment
        run: echo "Deployment script goes here"
